# Generated by Django 3.0.2 on 2020-02-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project2',
        ),
    ]
