# Generated by Django 3.0.2 on 2020-02-03 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_project2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 0, 21, 19, 407552), verbose_name='date published'),
        ),
    ]
