# Generated by Django 3.0.2 on 2020-02-03 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200203_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 0, 21, 50, 519146, tzinfo=utc), verbose_name='date published'),
        ),
    ]
