# Generated by Django 3.0.2 on 2020-02-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200203_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_content',
            new_name='project_code',
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(default="One of Ryan Alamo's coding projects."),
            preserve_default=False,
        ),
    ]
