# Generated by Django 3.0.2 on 2020-02-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200203_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_code',
        ),
        migrations.AddField(
            model_name='project',
            name='project_github',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(max_length=5000),
        ),
    ]
