# Generated by Django 3.0.2 on 2020-02-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200203_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_github',
            field=models.URLField(default=''),
        ),
    ]
